### ISSUE TITLE
Re-vendor / cleanup apitools as used in storage

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#1186]
Work plan:

- [x] Pull in the subset we use as a non-temporary fork (e..g, `gcloud._apitools`). #1189
- [x] Get it to 100% unit test coverage using our normal testing style. #1190, #1191, #1191, #1192, #1193, #1196, #1207 
- [x] Rename it `gcloud.streaming` so `nose` finds its tests. #1208 
- [ ] Remove unused bits. #1209 
- [ ] Make it fit our coding standards. #1210

**Comment by dhermes** [comment]
IMO this needs to go in core. As a start you could pull the multi-part message stuff into core?

**Comment by tseaver** [comment]
> IMO this needs to go in core.

ATM, I'm pulling the code into a `gcloud/_apitools` sub-package:  this will include the `transfer` and `http_wrapper` modules we use directly, plus those they pull in (`util`, `exceptions`, `buffered_stream`, and `stream_slice`).

I have these modules imported on a branch, and am adding from-scratch test coverage to them one by one.  Once coverage is complete, I intend to strip deadwood (any APIs we don't use), and then make the modules conform to our standards.

> As a start you could pull the multi-part message stuff into core?

I'm not sure which multi-part stuff you mean:  is it the bits currently in `gcloud.storage.batch`?

**Comment by dhermes** [comment]
I like the approach.

----

> is it the bits currently in `gcloud.storage.batch`?

Yup

**Comment by craigcitro** [comment]
FWIW, apitools is getting more external love via the cloudsdk folks. in particular, they cleaned up the google-apputils and gflags dependencies.

given that, it might be worth using? (i don't remember how much of apitools you use.)

**Comment by tseaver** [comment]
@craigcitro we basically use only the `transfer.Download` and `transfer.Upload` classes.

**Comment by craigcitro** [comment]
k. forking may well be the better road.

**Comment by dhermes** [comment]
@craigcitro We didn't have time to wait and assumed it would be getting left behind. To me, the fact that there are still no docs does not scream "use this, it's cared for".

**Comment by dhermes** [comment]
@tseaver Where does this stand?

**Comment by tseaver** [comment]
We're done, I think.
