### ISSUE TITLE
Enable auth via oauth2client: 3LO, Implicit from Environ, p12 and JSON service account

### ISSUE THREAD

**Issue by silvolu** [GoogleCloudPlatform/gcloud-python#335]
~~Please leave this on hold until we move the credential dance into oauth2client and update apitools, I will update this issue tomorrow.~~

Things to be done (added by @dhermes):
- [x] Use `oauth2client.client.GoogleCredentials.get_application_default()`. ~~This still is "open" due to google/oauth2client#93~~
- [x] Cover GAE service accounts (done via implicit in `get_application_default`)
- [x] Cover GCE service accounts (done via implicit in `get_application_default`)
- [x] Cover JSON service account credentials (done via implicit in `get_application_default`)
- [ ] Cover 3LO for people just getting started (#539)
- [x] Cover p12 service account credentials (moved in #412 to `gcloud.credentials.get_for_service_account_p12`)

**Comment by dhermes** [comment]
I'll try to tackle 3LO with a user-flow this week.

**Comment by dhermes** [comment]
@silvolu Adding 3LO is as simple as documenting

```
gcloud auth login
```

and then telling them to call

```python
from gcloud import credentials
creds = credentials.get_credentials()
```

If using just Datastore it's even more "just works":

```python
from gcloud import datastore
datastore.set_defaults()
```

Where do you think this should go?

**Comment by silvolu** [comment]
In the gcloud-node docs the auth bits are in the snippets contained in the 'getting started with gcloud' section, but I think this is more relevant to using the demos we provide with gcloud-python, so it should probably go in the 'API x in 10 seconds' sections. @jgeewax ?

**Comment by jgeewax** [comment]
Would it make sense to have an "Authentication" section at the same hierarchy level as each of the services ?

If I'm a developer and I'm trying to get set up, the "... in 10 seconds" pages are great, but I might want more detail about stuff. 3LO is a "more detail" thing. "... in 10 seconds" would be how the typical person does this (and typically, I'd use a service account with 2LO).

Thoughts?

**Comment by silvolu** [comment]
> "... in 10 seconds" would be how the typical person does this (and typically, I'd use a service account with 2LO).

It's currently showing how to use the demo, which is why it's where it makes sense to use 3LO (authorized with gcloud cli and reuse credentials vs create project, download key etc)

**Comment by jgeewax** [comment]
Might be worthwhile to toss in:

If I already have the Cloud SDK *and* the goal is "quickest way to get code actually working", then the gcloud auth login + datastore.set_defaults() is the fastest option. If they don't already have the SDK (which a lot of people don't -- nor do they want it...) then this is **not** the fastest way to get this moving.

Further, if we're measuring time from pip install to "running code on a server somewhere", then they'll have to use 2LO anyway, so they'll have to create a service account, pull down the key, and write code that uses that key (assuming they are **not** on GAE or GCE).

I'm in the group where I expect that talking to some outside service needs a "config.py" file of some sort (ie Django with settings.py) -- and I want to get that done right away. If there's magical "oh don't worry we hooked all the stuff together" then come deployment time I'm not the happiest camper because learning time is supposed to be coming to an end (maybe I'm the exception here). There's the edge case of "if I'm running in GCE", but unfortunately it is *absurdly* easy to screw this up (you have to click Advanced on your image **at creation time** and make sure that Datastore and whatever else is enabled -- otherwise you have to start over...)

Because of that, I'd want to highlight 2LO as "the way" to do this (including the "get a service account, pull down a JSON file, etc), and document 3LO as well, but not right in your face in the "... in 10 seconds" route.

Tell me if I'm totally crazy on this.

**Comment by dhermes** [comment]
So I'm with @jgeewax that our "endorsed" getting started should be using a JSON key for service account auth.

However, I think we should document somewhere that they can do 3LO using the `gcloud` CLI. In general it seems a "power user" type section may be useful somewhere.

**Comment by dhermes** [comment]
FYI I'm working on a `gcloud-auth` doc.

**Comment by dhermes** [comment]
Closing since #633 handles the only remaining bit (and will have less distracted comments)
