### ISSUE TITLE
Update Key API to be more user-friendly per design doc discussion

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#451]
Related ~~to #3 and~~
https://docs.google.com/document/d/1xKw8Tz6lfN5uOcv0my4uUgFSeDoRzwCLho2UGlBpqDU/edit

Plan to make this work:
- [x] Remove `Key.from_path` (since will be new constructor) (#456)
- [x] Remove all setters (#458)
- [x] Make `parent` re-use an instance (since immutable) (#459)
- [x] Make `Key` constructor act like `Key.from_path` (#460)
- [x] Make `Key.complete_key` method (needs better name) to act like `Key.id(new_id)` (#461)
- [x] Implement `Key.compare_to_proto` to check a key against a retrieved key (needs better name) (#462)
- [x] Require `dataset_id` on `Key` (may require removing `dataset_id` from `Key protos) (#463)
- [x] Add `parent` to constructor (#476)
- [x] ~~Update docstrings and other docs to reflect changes (including `__repr__`, probably shouldn't have `path`)~~ (Putting off bulk doc fixes until API is stable again)
- [x] ~~Change `Entity` constructor to only accept a `key`. (This can probably move to a new bug, which I have yet to file.)~~ (filed #484)

**Comment by dhermes** [comment]
Putting off bulk doc fixes until API is stable again
