### ISSUE TITLE
Remove datastore.Dataset class

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#477]
The replacement will be handled by a string when dataset ID is explicitly needed (which will only be for power users). Some functionality will be moved to `key.Key` and the rest to the `connection` module as free functions. In order to make use easier, they will also have versions in `__init__` which can use a default / implicit connection.

Steps to complete:

- [x] Make `set_default_connection` similar to [`set_default_dataset`][1] (#478)
- [x] Remove ~~`query()`,~~ `entity()`, and `transaction()` methods from `Dataset`, replace their use elsewhere. (#479)
- [x] Move `Dataset.get_entity` to `Key` (will impact elsewhere, e.g. `Entity.reload`) (#480)
- [x] Move ~~`save()` and `delete()` methods~~ `delete()` method from `Entity` to `Key` (#481)
- [x] Move `allocate_ids()` method from `Dataset` to ~~`connection`~~ `__init__` module as free function (#482)
- [x] Move `get_entities()` method from `Dataset` to ~~`connection`~~ `__init__` module as free function (#483)
- [x] Fix ~~#484, #485, #486~~ - Lots to do to re-make `Entity`, `Query`, and `Transaction` to not depend on `Dataset`
- [x] Remove all remnants of `Dataset` (e.g. `set_default_dataset`, `Entity._must_dataset`, and `_implicit_environ._DatastoreBase`)
- [x] Update stale documentation

**NOTE**: Don't close until `cyclic-import` in #480 is resolved.

See https://docs.google.com/document/d/1xKw8Tz6lfN5uOcv0my4uUgFSeDoRzwCLho2UGlBpqDU/edit for more.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/b79d8624950b3b205de20f527488dde7aa8c8cd8/gcloud/datastore/__init__.py#L61

**Comment by dhermes** [comment]
Re-opening until cyclic-imports are resolved.

**Comment by dhermes** [comment]
Closed for #517
