### ISSUE TITLE
Decouple Transaction from Connection

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#514]
~~After #509 is in,~~ We need to decouple `Transaction` from `Connection`  and allow `Transaction` to inherit from `Batch`.

Things to be done
-   [x] Change `Transaction` to inherit from `Batch` (#516)
-   [x] Track "active" batches / transactions in a thread-local stack (#518)
-   [x] Replace `Key.get()` with top-level `datastore.get()` (#520, #521, #522)
-   [x] Replace `Entity.save()` with top-level `datastore.put()` (#548)
-   [x] Replace `Key.delete()` witg top-level `datastore.delete()` (#522)
-   [x] Remove non-RPC methods `save_entity()` and `delete_entities()` from `Connection` (#550)
-   [x] Remove `Connection.mutation()`. (#550)
-   [x] Remove `Connection.transaction()` (#550)

Also relevant: #447 (`Transaction` and `Batch` should not have a `dataset_id` until they have objects to work with)

----
For reference, RPC [methods][1] are:

- Lookup
- RunQuery
- BeginTransaction
- Commit
- Rollback
- AllocateIds

[1]: https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/21e029b2657ebb15fef5429c90c4315326855fd1/proto/datastore_v1.proto#L573

**Comment by dhermes** [comment]
@tseaver Do you have irons in the fire on this? I'm happy to pick it up if you don't have bandwidth for it right now.

**Comment by tseaver** [comment]
@dhermes I'll tackle it this afternoon.

**Comment by dhermes** [comment]
Closing this out. @tseaver LMK if I missed something.
