### ISSUE TITLE
Implement "client" pattern for datastore

### ISSUE THREAD

**Issue by tseaver** [GoogleCloudPlatform/gcloud-python#944]
Per #861.

Steps:

- [x] Rename `gcloud.datastore.dataset.Dataset` -> `gcloud.datastore.client.Client`. (#946)
- [x] Unwind `_implicit_environ` usage within client. (#956)
- [x] Move `gcloud.datastore.api` functions to methods of `Client`. (#963)
- [x] Update `Client` to handle nesting of batches / transactions over primary connection. (#976)
- [x] Update domain objects making API requests to hold reference to `client`. (#978)
- [x] Update `Batch` and `Transaction` context managers to push themselves onto their client's stack. (#978)
- [x] Update domain object methods taking `connection` to accept `client`, falling back to `self.client`. (#978)
- [x] Remove remaining `_implicit_environ` usage. (#979)

**Comment by dhermes** [comment]
Thanks for the outline!

**Comment by dhermes** [comment]
@tseaver I am going to factor out `Client` as a base class in core. Will this cause problems for you?

**Comment by tseaver** [comment]
@dhermes go ahead for `pubsub` / `storage`, but please leave the one in `datastore` alone until after I'm done here.

**Comment by dhermes** [comment]
#955 is just in place as an example, I dropped the don't merge label on it.

I'd like to get #953 in before starting on `storage`. `pubsub` is all done (aside from the refactoring)
