### ISSUE TITLE
Implement "client" pattern for storage

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#952]
Similar to #944, per #861 

Taking #910 as a template, this is my proposed order of work:

- [x] Adding client class side-by-side existing (#964) (~~likely will factor out the pubsub client in `core` first, see #953~~)
- [x] ~~Adding factory constructors to client.~~ (Done by the parent class in #953)
- [x] Move methods from `storage.api` onto the client and remove `api` module (#973)
- [x] Replace client in places where a connection is used (#984, #987)
- [x] Drop the `_implicit_environ` module
- [x] Update regression tests (may just do this progressively over several PRs instead of a brain dump PR like #910 was)
- [x] Update docs (ditto here)
